events {
    worker_connections 1024;
}

http {
    limit_req_zone $binary_remote_addr zone=apilimit:10m rate=10r/s;    

    upstream iris-apis {
        server mlops-iris-api:8000;
    }

    # Defining our http server
    server {
        listen 80;
        server_name localhost;

        # Redirects all HTTP requests to HTTPS
        return 301 https://$host$request_uri;
    }

    # Defining our new https server
    server {
        listen 443 ssl; # Listen on port 443 and enable SSL
        server_name localhost; # Domain name or IP that this server manages

        # Paths to SSL certificates inside the Nginx container
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        # SSL protocols and ciphers
        ssl_protocols TLSv1.2 TLSv1.3; # Only allow modern versions of TLS
        ssl_ciphers HIGH:!aNULL:!MD5; # List of allowed cipher suites
        ssl_prefer_server_ciphers on; # Prefer server ciphers

        location /nginx_status {
            stub_status on; 
            access_log off; 
            allow localhost; 
            allow 172.18.0.0/16; 
            deny all;
        }

        location /predict {
            auth_basic "API Access Protected";
            auth_basic_user_file /etc/nginx/.htpasswd;
   
            limit_req zone=apilimit burst=5 nodelay;

            proxy_pass http://iris-apis;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
